services:
#    esgi_user.example:
#        class: ESGI\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
#    tellmedia_user.example:
#        class: %tellmedia_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
   esgi_user.registration.form.type:
        class: ESGI\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: esgi_user_registration }
