imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true
            timestampable: true # not needed: listeners are not enabled by default

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: ESGI\UserBundle\Entity\User
    registration:
        form:
            type: esgi_user_registration

sonata_admin:
    title: ESGI Blog
    templates:
        layout:                         ESGIBlogBundle:Admin:standard_layout.html.twig
        ajax:                           SonataAdminBundle::ajax_layout.html.twig
        list:                           SonataAdminBundle:CRUD:list.html.twig
        show:                           SonataAdminBundle:CRUD:show.html.twig
        show_compare:                   SonataAdminBundle:CRUD:show_compare.html.twig
        edit:                           SonataAdminBundle:CRUD:edit.html.twig
        history:                        SonataAdminBundle:CRUD:history.html.twig
        preview:                        SonataAdminBundle:CRUD:preview.html.twig
        delete:                         SonataAdminBundle:CRUD:delete.html.twig
        batch:                          SonataAdminBundle:CRUD:list__batch.html.twig
        action:                         SonataAdminBundle:CRUD:action.html.twig
        select:                         SonataAdminBundle:CRUD:list__select.html.twig
        filter:                         SonataAdminBundle:Form:filter_admin_fields.html.twig
        dashboard:                      SonataAdminBundle:Core:dashboard.html.twig
        search:                         SonataAdminBundle:Core:search.html.twig
        batch_confirmation:             SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:                 SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:                SonataAdminBundle:CRUD:base_list_field.html.twig
        list_block:                     SonataAdminBundle:Block:block_admin_list.html.twig
        user_block:                     SonataAdminBundle:Core:user_block.html.twig
        add_block:                      SonataAdminBundle:Core:add_block.html.twig
        pager_links:                    SonataAdminBundle:Pager:links.html.twig
        pager_results:                  SonataAdminBundle:Pager:results.html.twig
        tab_menu_template:              SonataAdminBundle:Core:tab_menu_template.html.twig
        history_revision_timestamp:     SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:       SonataAdminBundle:Helper:short-object-description.html.twig
        search_result_block:            SonataAdminBundle:Block:block_search_result.html.twig
    security:
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

sonata_doctrine_orm_admin:
    templates:
        form:
            - ESGIBlogBundle:Admin:form_admin_fields.html.twig



sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

#JMS BUNDLE (utilise pour Rest Web service)
jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"

#Api Doc
nelmio_api_doc: ~

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%
    theme:
        simple:
            theme: "modern"
