esgi_blog_homepage:
    path:     /welcome/{name}
    defaults: { _controller: ESGIBlogBundle:Default:index }
esgi_blog_article_see:
    path:     /

add:
    path:     /add
    defaults: { _controller: ESGIBlogBundle:Article:add }
edit:
    path:     /edit
    defaults: { _controller: ESGIBlogBundle:Article:edit }
suggestArticle:
    path:     /suggestArticle
    defaults: { _controller: ESGIBlogBundle:Article:suggestArticle }

see:
    path:     /article/{id}
    defaults: { _controller: ESGIBlogBundle:Article:see }
    requirements:
        id: \d+

delete:
    path:     /delete
    defaults: { _controller: ESGIBlogBundle:Article:delete }

articles:
    path:     /articles/{page}/{id}
    defaults: { _controller: ESGIBlogBundle:Article:articles, page: 1, id: 0 }
    requirements:
        page: \d*
        id:   \d+

suggest:
    path:     /suggest/{page}
    defaults: { _controller: ESGIBlogBundle:Article:suggest, page: 1 }
    requirements:
        page: \d*
get_categories:
    path:     /categories
    defaults: { _controller: ESGIBlogBundle:Category:getCategories }

post_categories:
    path:     /add-category
    defaults: { _controller: ESGIBlogBundle:Category:postCategories }

put_category:
    path:     /putCategory
    defaults: { _controller: ESGIBlogBundle:Category:putCategory }

add_comment:
    path:    /add-comment/{id}
    defaults: { _controller: ESGIBlogBundle:Comment:postComments }
    requirements:
        id: \d+

edit_comment:
    path:    /edit-comment/{id}
    defaults: { _controller: ESGIBlogBundle:Comment:putComment }
    requirements:
        id: \d+
