services:

     ESGI.BlogBundle.Admin.Article:
         class: ESGI\BlogBundle\Admin\ArticleAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: Gestion Des Articles, label: Articles }
         arguments: [null, ESGI\BlogBundle\Entity\Article, ESGIBlogBundle:ArticleAdmin]
         calls:
             - [ setSecurityContext, [ @security.context ] ]
     ESGI.BlogBundle.Admin.Image:
              class: ESGI\BlogBundle\Admin\ImageAdmin
              tags:
                  - { name: sonata.admin, manager_type: orm, group: Gestion Des Articles, label: Image }
              arguments: [null, ESGI\BlogBundle\Entity\Image, ESGIBlogBundle:ImageAdmin]
     ESGI.BlogBundle.Admin.Category:
              class: ESGI\BlogBundle\Admin\CategoryAdmin
              tags:
                  - { name: sonata.admin, manager_type: orm, group: Gestion Des Articles, label: Categorie }
              arguments: [null, ESGI\BlogBundle\Entity\Category, ESGIBlogBundle:CategoryAdmin]
              calls:
                  - [ setSecurityContext, [ @security.context ] ]
     ESGI.BlogBundle.Admin.User:
              class: ESGI\BlogBundle\Admin\UserAdmin
              tags:
                  - { name: sonata.admin, manager_type: orm, group: Gestion Des Utilisateurs, label: Utilisateur }
              arguments: [null, ESGI\UserBundle\Entity\User, ESGIBlogBundle:UserAdmin]
              calls:
                  - [ setSecurityContext, [ @security.context ] ]
     ESGI.BlogBundle.Admin.Comment:
              class: ESGI\BlogBundle\Admin\CommentAdmin
              tags:
                  - { name: sonata.admin, manager_type: orm, group: Gestion Des Commentaires, label: Commentaires }
              arguments: [null, ESGI\BlogBundle\Entity\Comment, ESGIBlogBundle:CommentAdmin]